<a href="https://colab.research.google.com/github/rakeshghosal9/ML_Practice/blob/main/NLP_NGram.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('sample_data/BagOfWords.csv')

In [3]:
df

text  Output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range = (2,2))

In [6]:
bow = cv.fit_transform(df['text'])

In [7]:
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [8]:
#each sentence has been converted to a vector where it looks for fequency of vocabulary form each sentence
for i in range(len(df)):
    print(bow[i].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]
[[0 1 0 0 0 1]]


In [9]:
#even if a new sentence is introduced, it doesn't impact as it just focuses on the words present in vocabulary
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[1, 0, 0, 0, 0, 1]])

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
#With ngram_range = 1,2 means both unigram and bigram words will be present
cv = CountVectorizer(ngram_range = (1,2))
bow = cv.fit_transform(df['text'])
print(cv.vocabulary_)

{'people': 4, 'watch': 7, 'campusx': 0, 'people watch': 5, 'watch campusx': 8, 'campusx watch': 1, 'write': 9, 'comment': 3, 'people write': 6, 'write comment': 10, 'campusx write': 2}


In [16]:
from sklearn.feature_extraction.text import CountVectorizer
#With ngram_range = 1,3 means both unigram, bigram and trigram words will be present
cv = CountVectorizer(ngram_range = (1,3))
bow = cv.fit_transform(df['text'])
print(cv.vocabulary_)
print("Total Vocabulary Count: " + str(len(cv.vocabulary_)))

{'people': 6, 'watch': 11, 'campusx': 0, 'people watch': 7, 'watch campusx': 12, 'people watch campusx': 8, 'campusx watch': 1, 'campusx watch campusx': 2, 'write': 13, 'comment': 5, 'people write': 9, 'write comment': 14, 'people write comment': 10, 'campusx write': 3, 'campusx write comment': 4}
Total Vocabulary Count: 15


In [19]:
from sklearn.feature_extraction.text import CountVectorizer
#With ngram_range = 2,3 means bigram and trigram words will be present, not unigram
cv = CountVectorizer(ngram_range = (2,3))
bow = cv.fit_transform(df['text'])
print(cv.vocabulary_)
print("Total Vocabulary Count: " + str(len(cv.vocabulary_)))

{'people watch': 4, 'watch campusx': 8, 'people watch campusx': 5, 'campusx watch': 0, 'campusx watch campusx': 1, 'people write': 6, 'write comment': 9, 'people write comment': 7, 'campusx write': 2, 'campusx write comment': 3}
Total Vocabulary Count: 10
